
/* Kefu Zhu */
/* HW1 Submission */

/* Remember to save this template file as HW1_YourNetID.sas */

/* This ODS statement followed by the one at the end of the file
   will put all of the output generated by the code in between
   into a single PDF file. That is your report for HW1. */
ods pdf file='C:\440\hw1\HW1_kefuzhu2.pdf' ;
/*Set up library*/
libname hw1 'C:\440\hw1';
/*Create titles and footnotes*/
title1 STAT 440 Homework 1;
title2 January 30, 2016;
title3 Kefu Zhu;
footnote1 Kefu Zhu;
/* Exercise 1 */
/*(a)*/
ods text = 'Exercise 1';
ods text = '(a)';
proc contents data = sashelp.pricedata;
run;
/*(b)*/
data pricing_kefuzhu2;
	 set sashelp.pricedata;
	 where sale > 400 & (price-cost)<30;
	 keep Date Sale Price Discount Cost ProductName;
	 label Sale='Units Sold';
	 format date date9.
	 		price dollar10.2
	 		cost dollar10.2
			discount percent8.;
run;
/*(c)*/
ods text = '(c)';
proc contents data = pricing_kefuzhu2;
run;
/*(d)*/
ods text = '(d)';
proc print data = pricing_kefuzhu2 label;
run;
/* Exercise 2 */
/*(a)*/
ods text = 'Exercise 2';
ods text = '(a)';
proc contents data = hw1.employee_roster;
run;
/*(b)*/
data top_earners_kefuzhu2;
	set hw1.employee_roster;
	where Salary > 80000;
	label Job_Title = 'Position'
		  Salary = 'Yearly Salary';
run;
/*(c)*/
ods text = '(c)';
proc print data = top_earners_kefuzhu2 label;
	var Employee_Name Job_Title Salary;
run;
/*(d)*/
ods text = '(d)';
proc print data = hw1.employee_roster;
	where Employee_Gender = 'M' &
		  Section = 'Administration' &
		  28000 <= Salary <= 35000;
	var Employee_Name Employee_Gender Section Salary;
run;
/*(e)*/
ods text = '(e)';
proc print data = hw1.employee_roster;
	where Employee_Name like 'K%'|
		  Employee_Name like 'L%'|
		  Employee_Name like 'M%'|
		  Employee_Name like 'N%';
	var Employee_Name Employee_ID Org_Group;
run;

title;
footnote;
ods pdf close;
